#!/usr/bin/env bash

set -e

CONFIG="base.conf.yaml"
CONFIG_MACOS="macos.conf.yaml"
CONFIG_UBUNTU="ubuntu_packages.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"


# Run MacOS or Ubuntu config depending on OS
OS=`uname`
case $OS in 
    'Darwin')
        "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brewfile -c "${CONFIG_MACOS}" "${@}"
	;;
    'Linux')
	if [ $UID != 0 ] && [ -n "$(lsb_release -d | awk -F"\t" '{print $2}' | grep Ubuntu)" ]; then
    	    sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-apt -c "${CONFIG_UBUNTU}" "${@}"
	else
	    echo "Script only supports Ubuntu presently... you better fix that..."
	    exit $?
	fi
	;;
    *)
	echo "Unknown OS: $OS, not doing anything"
        ;;
esac

# Install base config - this goes at end because it changes shell and vimplug depends on curl
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
