#!/bin/bash

echo "Updating Apt"
sudo apt update && apt list --upgradable && apt upgrade

echo "Updating VIM Plugins"
nvim +PlugUpgrade +PlugUpdate +qall > /dev/null

echo "Upgrading dotfile submodules"
git submodule update --recursive --remote
echo "You should consider commiting the .dotfiles repo if there were upstream changes"
