#!/bin/bash

echo "Updating Brew"
brew update

echo "Upgrading Brew"
brew outdated && brew upgrade

echo "Upgrading Brew Casks"
Brew cask outdated && brew cask upgrade

echo "Upgrading dotfile submodules"
git submodule update --recursive --remote
echo "You should consider commiting the .dotfiles repo if there were upstream changes"
