#!/bin/bash

echo "Updating Brew"
brew update

echo "Upgrading Brew"
brew outdated && brew upgrade

echo "Upgrading Brew Casks"
brew outdated --cask && brew upgrade --cask

echo "Updating VIM Plugins"
nvim +PlugUpgrade +PlugUpdate +qall > /dev/null

echo "Upgrading dotfile submodules"
git submodule update --recursive --remote
echo "You should consider commiting the .dotfiles repo if there were upstream changes"
